spring.application.name=lab1arq
server.port=${PORT:8088}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/udeabank}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://lab1arq-2026-ii.jorge-ruizf.workers.dev,https://*-lab1arq-2026-ii.jorge-ruizf.workers.dev,http://localhost:4321}
